// src/app/(dashboard)/dashboard/invitations/new/page.tsx
import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import Topbar from '@/components/layout/Topbar'
import InvitationForm from '@/components/invitations/InvitationForm'
import { Button } from '@/components/ui/button'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export const metadata = { title: 'New Invitation – Muyenzi' }

export default async function NewInvitationPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: profile } = await supabase.from('users').select('company_id').eq('id', user.id).single()
  if (!profile) redirect('/login')

  const { data: sites } = await supabase.from('sites').select('id, name').eq('company_id', profile.company_id)
  const { data: hosts } = await supabase.from('users').select('id, full_name').eq('company_id', profile.company_id)

  return (
    <div className="flex flex-col">
      <Topbar title="New Invitation" />
      <div className="p-6 max-w-2xl">
        <Button variant="ghost" size="sm" className="mb-4 -ml-2" asChild>
          <Link href="/dashboard/invitations"><ArrowLeft className="h-4 w-4 mr-1" /> Back</Link>
        </Button>
        <InvitationForm
          companyId={profile.company_id}
          hostId={user.id}
          sites={sites ?? []}
          hosts={hosts ?? []}
        />
      </div>
    </div>
  )
}

// pages/dashboard/invitations/new.vue
<script setup lang="ts">
definePageMeta({ layout: 'dashboard' })
useHead({ title: 'New Invitation – Muyenzi' })

const supabase = useSupabaseClient()
const { user } = useUser()

const sites = ref<{ id: string; name: string }[]>([])
const hosts = ref<{ id: string; full_name: string }[]>([])

onMounted(async () => {
  if (!user.value) return
  const [{ data: s }, { data: h }] = await Promise.all([
    supabase.from('sites').select('id, name').eq('company_id', user.value.company_id),
    supabase.from('users').select('id, full_name').eq('company_id', user.value.company_id),
  ])
  sites.value = s ?? []
  hosts.value = h ?? []
})
</script>

<template>
  <div class="flex flex-col h-full">
    <LayoutTopbar title="New Invitation" description="Pre-register a visitor" />

    <div class="flex-1 overflow-y-auto p-6">
      <UButton variant="ghost" size="sm" to="/dashboard/invitations" icon="i-lucide-arrow-left" class="mb-6 -ml-2">
        Back
      </UButton>
      <InvitationsInvitationForm
        v-if="user"
        :company-id="user.company_id"
        :host-id="user.id"
        :sites="sites"
        :hosts="hosts"
      />
    </div>
  </div>
</template>
