// components/shared/ExportMenu.vue
<script setup lang="ts">
defineProps<{ companyId: string }>()

function download(format: 'csv' | 'pdf', companyId: string) {
  window.open(`/api/export/${format}?company_id=${companyId}`, '_blank')
}

const items = (companyId: string) => [
  [
    { label: 'Export as CSV', icon: 'i-lucide-file-spreadsheet', click: () => download('csv', companyId) },
    { label: 'Export as PDF', icon: 'i-lucide-file-text', click: () => download('pdf', companyId) },
  ],
]
</script>

<template>
  <UDropdown :items="items(companyId)" :popper="{ placement: 'bottom-end' }">
    <UButton variant="outline" color="gray" icon="i-lucide-download" size="sm">Export</UButton>
  </UDropdown>
</template>

// src/components/shared/ExportMenu.tsx
'use client'

import { Download } from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'

export default function ExportMenu({ companyId }: { companyId: string }) {
  function download(format: 'csv' | 'pdf') {
    window.open(`/api/export/${format}?company_id=${companyId}`, '_blank')
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger render={<Button variant="outline" size="sm" />}>
        <Download className="h-4 w-4 mr-2" /> Export
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={() => download('csv')}>Export as CSV</DropdownMenuItem>
        <DropdownMenuItem onClick={() => download('pdf')}>Export as PDF</DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
