// components/shared/QRCodeDisplay.vue
<script setup lang="ts">
import QRCode from 'qrcode'

const props = defineProps<{
  data: string
  size?: number
}>()

const dataUrl = ref('')

onMounted(async () => {
  dataUrl.value = await QRCode.toDataURL(props.data, {
    width: props.size ?? 200,
    margin: 1,
    color: { dark: '#0f172a', light: '#ffffff' },
  })
})
</script>

<template>
  <div class="flex items-center justify-center">
    <img v-if="dataUrl" :src="dataUrl" :width="size ?? 200" :height="size ?? 200" alt="QR Code" class="rounded-lg" />
    <div v-else class="bg-gray-100 rounded-lg animate-pulse" :style="{ width: `${size ?? 200}px`, height: `${size ?? 200}px` }" />
  </div>
</template>

// src/components/shared/QRCodeDisplay.tsx
'use client'

import { useEffect, useRef } from 'react'
import QRCode from 'qrcode'

interface Props {
  data: string
  size?: number
}

export default function QRCodeDisplay({ data, size = 200 }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null)

  useEffect(() => {
    if (!canvasRef.current) return
    QRCode.toCanvas(canvasRef.current, data, {
      width: size,
      margin: 2,
      color: { dark: '#0f172a', light: '#ffffff' },
    })
  }, [data, size])

  return <canvas ref={canvasRef} className="rounded-lg" />
}
