// components/layout/MarketingHeader.vue
<script setup lang="ts">
const navLinks = [
  { href: '/features', label: 'Features' },
  { href: '/pricing', label: 'Pricing' },
  { href: '/contact', label: 'Contact' },
]
</script>

<template>
  <header class="border-b border-slate-100 bg-white/90 backdrop-blur-sm sticky top-0 z-50">
    <div class="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
      <NuxtLink to="/" class="flex items-center gap-2.5">
        <div
          class="h-8 w-8 rounded-lg flex items-center justify-center"
          style="background: linear-gradient(135deg, #6366f1 0%, #818cf8 100%)"
        >
          <span class="text-white font-bold text-xs">M</span>
        </div>
        <span class="font-bold text-slate-900">muyenzi</span>
      </NuxtLink>

      <nav class="hidden md:flex items-center gap-8">
        <NuxtLink
          v-for="link in navLinks"
          :key="link.href"
          :to="link.href"
          class="text-sm text-slate-600 hover:text-slate-900 transition-colors"
        >
          {{ link.label }}
        </NuxtLink>
      </nav>

      <div class="flex items-center gap-3">
        <UButton variant="ghost" color="gray" to="/login" size="sm">Sign in</UButton>
        <UButton to="/signup" size="sm">Get started</UButton>
      </div>
    </div>
  </header>
</template>

// src/components/layout/MarketingHeader.tsx
import Link from 'next/link'
import { Button } from '@/components/ui/button'

export default function MarketingHeader() {
  return (
    <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-sm border-b">
      <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
        <Link href="/" className="flex items-center gap-2">
          <div className="h-8 w-8 rounded-lg bg-slate-900 flex items-center justify-center">
            <span className="text-white font-bold text-sm">M</span>
          </div>
          <span className="font-semibold text-slate-900 text-lg">muyenzi</span>
        </Link>
        <nav className="hidden md:flex items-center gap-8 text-sm text-slate-600">
          <Link href="/features" className="hover:text-slate-900 transition-colors">Features</Link>
          <Link href="/pricing" className="hover:text-slate-900 transition-colors">Pricing</Link>
          <Link href="/contact" className="hover:text-slate-900 transition-colors">Contact</Link>
        </nav>
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="sm" asChild>
            <Link href="/login">Sign in</Link>
          </Button>
          <Button size="sm" asChild>
            <Link href="/signup">Start free trial</Link>
          </Button>
        </div>
      </div>
    </header>
  )
}
