// src/app/(dashboard)/dashboard/sites/[siteId]/page.tsx
'use client'

import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { useRouter, useParams } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import Topbar from '@/components/layout/Topbar'
import { toast } from 'sonner'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

const schema = z.object({
  name: z.string().min(2),
  address: z.string().optional(),
})
type FormData = z.infer<typeof schema>

export default function EditSitePage() {
  const { siteId } = useParams<{ siteId: string }>()
  const router = useRouter()
  const supabase = createClient()

  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<FormData>({
    resolver: zodResolver(schema),
  })

  useEffect(() => {
    supabase.from('sites').select('*').eq('id', siteId).single().then(({ data }) => {
      if (data) reset({ name: data.name, address: data.address ?? '' })
    })
  }, [siteId]) // eslint-disable-line react-hooks/exhaustive-deps

  async function onSubmit(data: FormData) {
    const { error } = await supabase.from('sites').update({
      name: data.name,
      address: data.address || null,
    }).eq('id', siteId)
    if (error) { toast.error(error.message); return }
    toast.success('Site updated')
    router.push('/dashboard/sites')
    router.refresh()
  }

  return (
    <div className="flex flex-col">
      <Topbar title="Edit Site" />
      <div className="p-6 max-w-lg">
        <Button variant="ghost" size="sm" className="mb-4 -ml-2" asChild>
          <Link href="/dashboard/sites"><ArrowLeft className="h-4 w-4 mr-1" /> Back</Link>
        </Button>
        <Card>
          <CardHeader><CardTitle>Edit site details</CardTitle></CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
              <div className="space-y-2">
                <Label>Site name *</Label>
                <Input {...register('name')} />
                {errors.name && <p className="text-sm text-red-600">{errors.name.message}</p>}
              </div>
              <div className="space-y-2">
                <Label>Address</Label>
                <Input {...register('address')} />
              </div>
              <div className="flex gap-3 pt-2">
                <Button type="button" variant="outline" onClick={() => router.back()}>Cancel</Button>
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting ? 'Saving…' : 'Save Changes'}
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

// pages/dashboard/sites/[siteId].vue
<script setup lang="ts">
import { z } from 'zod'

definePageMeta({ layout: 'dashboard' })

const supabase = useSupabaseClient()
const route = useRoute()
const toast = useToast()
const siteId = route.params.siteId as string

const state = reactive({ name: '', address: '' })
const loading = ref(false)
const fetchLoading = ref(true)

useHead({ title: 'Edit Site – Muyenzi' })

const schema = z.object({
  name: z.string().min(2, 'Site name is required'),
  address: z.string().optional(),
})

onMounted(async () => {
  const { data } = await supabase.from('sites').select('*').eq('id', siteId).single()
  if (!data) { await navigateTo('/dashboard/sites'); return }
  state.name = data.name
  state.address = data.address ?? ''
  fetchLoading.value = false
})

async function onSubmit() {
  loading.value = true
  const { error } = await supabase.from('sites').update({
    name: state.name,
    address: state.address || null,
  }).eq('id', siteId)
  loading.value = false
  if (error) {
    toast.add({ title: 'Error', description: error.message, color: 'red' })
    return
  }
  toast.add({ title: 'Site updated', color: 'green' })
  await navigateTo('/dashboard/sites')
}
</script>

<template>
  <div class="flex flex-col h-full">
    <LayoutTopbar title="Edit Site" />

    <div class="p-6 max-w-lg">
      <UButton variant="ghost" size="sm" to="/dashboard/sites" icon="i-lucide-arrow-left" class="mb-4 -ml-2">
        Back
      </UButton>
      <UCard v-if="!fetchLoading">
        <template #header>
          <h2 class="font-bold text-gray-900">Edit site</h2>
        </template>
        <UForm :schema="schema" :state="state" class="space-y-4" @submit="onSubmit">
          <UFormGroup label="Site name" name="name" required>
            <UInput v-model="state.name" />
          </UFormGroup>
          <UFormGroup label="Address" name="address">
            <UInput v-model="state.address" />
          </UFormGroup>
          <div class="flex gap-3 pt-2">
            <UButton variant="outline" @click="navigateTo('/dashboard/sites')">Cancel</UButton>
            <UButton type="submit" :loading="loading">Save Changes</UButton>
          </div>
        </UForm>
      </UCard>
    </div>
  </div>
</template>
