// src/app/(dashboard)/dashboard/sites/page.tsx
import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { Building2, Plus, MapPin } from 'lucide-react'
import { Button, Card, CardBody } from '@heroui/react'
import Topbar from '@/components/layout/Topbar'
import Link from 'next/link'
import { formatDate } from '@/lib/utils/format'
import DeleteSiteButton from './DeleteSiteButton'

export const metadata = { title: 'Sites – Muyenzi' }

export default async function SitesPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: profile } = await supabase.from('users').select('company_id, role').eq('id', user.id).single()
  if (!profile) redirect('/login')

  const { data: sites } = await supabase
    .from('sites')
    .select('*')
    .eq('company_id', profile.company_id)
    .order('created_at', { ascending: false })

  const canManage = ['admin', 'site_manager'].includes(profile.role)

  return (
    <div className="flex flex-col h-full">
      <Topbar title="Sites" description="Manage your locations and kiosk access" />

      <div className="flex-1 overflow-y-auto p-6 space-y-6">
        <div className="flex items-center justify-between">
          <p className="text-sm text-default-400 font-medium">
            {sites?.length ?? 0} location{sites?.length !== 1 ? 's' : ''}
          </p>
          {canManage && (
            <Button
              as={Link}
              href="/dashboard/sites/new"
              color="primary"
              variant="shadow"
              size="sm"
              radius="lg"
              className="font-semibold"
              startContent={<Plus className="h-4 w-4" />}
            >
              Add Site
            </Button>
          )}
        </div>

        {!sites?.length ? (
          <Card shadow="md" radius="lg" className="bg-content1">
            <CardBody className="flex flex-col items-center justify-center py-20 text-center">
              <div className="h-16 w-16 rounded-full bg-default-100 flex items-center justify-center mb-4">
                <Building2 className="h-8 w-8 text-default-300" />
              </div>
              <h3 className="font-bold text-foreground text-lg mb-1">No sites yet</h3>
              <p className="text-sm text-default-400 mb-5">Add your first location to start managing visitors.</p>
              {canManage && (
                <Button
                  as={Link}
                  href="/dashboard/sites/new"
                  color="primary"
                  variant="shadow"
                  radius="lg"
                  className="font-semibold"
                  startContent={<Plus className="h-4 w-4" />}
                >
                  Add Site
                </Button>
              )}
            </CardBody>
          </Card>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
            {sites.map(site => (
              <Card
                key={site.id}
                shadow="md"
                radius="lg"
                className="bg-content1 hover:shadow-lg transition-shadow duration-200"
              >
                <CardBody className="p-5">
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-start gap-3 min-w-0">
                      <div className="mt-0.5 h-10 w-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
                        <Building2 className="h-5 w-5 text-primary" />
                      </div>
                      <div className="min-w-0">
                        <p className="font-bold text-foreground">{site.name}</p>
                        {site.address && (
                          <div className="flex items-center gap-1 mt-1">
                            <MapPin className="h-3 w-3 text-default-400 shrink-0" />
                            <p className="text-xs text-default-400 truncate">{site.address}</p>
                          </div>
                        )}
                        <p className="text-xs text-default-300 mt-1.5">Added {formatDate(site.created_at)}</p>
                      </div>
                    </div>
                    {canManage && <DeleteSiteButton siteId={site.id} siteName={site.name} />}
                  </div>

                  <div className="mt-4 pt-4 flex gap-2" style={{ borderTop: '1px solid var(--border)' }}>
                    <Button
                      as={Link}
                      href={`/kiosk/${site.id}`}
                      target="_blank"
                      variant="flat"
                      color="default"
                      size="sm"
                      radius="lg"
                      className="flex-1 font-semibold"
                    >
                      Open Kiosk
                    </Button>
                    {canManage && (
                      <Button
                        as={Link}
                        href={`/dashboard/sites/${site.id}`}
                        variant="flat"
                        color="primary"
                        size="sm"
                        radius="lg"
                        className="flex-1 font-semibold"
                      >
                        Edit
                      </Button>
                    )}
                  </div>
                </CardBody>
              </Card>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

// pages/dashboard/sites/index.vue
<script setup lang="ts">
import type { Site } from '~/types/database'

definePageMeta({ layout: 'dashboard' })
useHead({ title: 'Sites – Muyenzi' })

const supabase = useSupabaseClient()
const { user, can } = useUser()
const toast = useToast()

const sites = ref<Site[]>([])
const loading = ref(true)
const canManage = computed(() => can('manage_sites'))

async function fetchSites() {
  if (!user.value) return
  const { data } = await supabase
    .from('sites')
    .select('*')
    .eq('company_id', user.value.company_id)
    .order('created_at', { ascending: false })
  sites.value = (data ?? []) as Site[]
  loading.value = false
}

async function deleteSite(id: string, name: string) {
  const { error } = await supabase.from('sites').delete().eq('id', id)
  if (error) {
    toast.add({ title: 'Error', description: error.message, color: 'red' })
    return
  }
  toast.add({ title: 'Site deleted', description: `${name} has been removed.` })
  sites.value = sites.value.filter(s => s.id !== id)
}

onMounted(fetchSites)
</script>

<template>
  <div class="flex flex-col h-full">
    <LayoutTopbar title="Sites" description="Manage your locations and kiosk access" />

    <div class="flex-1 overflow-y-auto p-6 space-y-6">
      <div class="flex items-center justify-between">
        <p class="text-sm text-gray-400 font-medium">
          {{ sites.length }} location{{ sites.length !== 1 ? 's' : '' }}
        </p>
        <UButton v-if="canManage" to="/dashboard/sites/new" icon="i-lucide-plus">Add Site</UButton>
      </div>

      <!-- Empty state -->
      <UCard v-if="!loading && !sites.length">
        <div class="flex flex-col items-center justify-center py-20 text-center">
          <div class="h-16 w-16 rounded-full bg-gray-100 flex items-center justify-center mb-4">
            <UIcon name="i-lucide-building-2" class="h-8 w-8 text-gray-300" />
          </div>
          <h3 class="font-bold text-gray-900 text-lg mb-1">No sites yet</h3>
          <p class="text-sm text-gray-400 mb-5">Add your first location to start managing visitors.</p>
          <UButton v-if="canManage" to="/dashboard/sites/new" icon="i-lucide-plus">Add Site</UButton>
        </div>
      </UCard>

      <!-- Sites grid -->
      <div v-else class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        <UCard v-for="site in sites" :key="site.id" class="hover:shadow-md transition-shadow">
          <div class="flex items-start justify-between gap-3">
            <div class="flex items-start gap-3 min-w-0">
              <div class="mt-0.5 h-10 w-10 rounded-xl bg-primary-50 flex items-center justify-center shrink-0">
                <UIcon name="i-lucide-building-2" class="h-5 w-5 text-primary-500" />
              </div>
              <div class="min-w-0">
                <p class="font-bold text-gray-900">{{ site.name }}</p>
                <div v-if="site.address" class="flex items-center gap-1 mt-1">
                  <UIcon name="i-lucide-map-pin" class="h-3 w-3 text-gray-400 shrink-0" />
                  <p class="text-xs text-gray-400 truncate">{{ site.address }}</p>
                </div>
                <p class="text-xs text-gray-300 mt-1.5">Added {{ formatDate(site.created_at) }}</p>
              </div>
            </div>
            <UButton
              v-if="canManage"
              icon="i-lucide-trash-2"
              color="red"
              variant="ghost"
              size="xs"
              @click="deleteSite(site.id, site.name)"
            />
          </div>

          <div class="mt-4 pt-4 flex gap-2 border-t border-gray-100">
            <UButton
              :to="`/kiosk/${site.id}`"
              target="_blank"
              variant="soft"
              color="gray"
              size="sm"
              class="flex-1"
            >
              Open Kiosk
            </UButton>
            <UButton
              v-if="canManage"
              :to="`/dashboard/sites/${site.id}`"
              variant="soft"
              size="sm"
              class="flex-1"
            >
              Edit
            </UButton>
          </div>
        </UCard>
      </div>
    </div>
  </div>
</template>
