// src/app/(auth)/auth/reset-password/page.tsx
'use client'

export const dynamic = 'force-dynamic'

import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'

const schema = z.object({ email: z.string().email() })
type FormData = z.infer<typeof schema>

export default function ResetPasswordPage() {
  const [sent, setSent] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormData>({
    resolver: zodResolver(schema),
  })

  async function onSubmit(data: FormData) {
    setError(null)
    const { createClient } = await import('@/lib/supabase/client')
    const supabase = createClient()
    const { error } = await supabase.auth.resetPasswordForEmail(data.email, {
      redirectTo: `${window.location.origin}/auth/callback?next=/dashboard/settings/profile`,
    })
    if (error) { setError(error.message); return }
    setSent(true)
  }

  if (sent) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Check your email</CardTitle>
          <CardDescription>We&apos;ve sent a password reset link to your email.</CardDescription>
        </CardHeader>
        <CardContent>
          <Button variant="outline" className="w-full" asChild>
            <Link href="/login">Back to sign in</Link>
          </Button>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Reset password</CardTitle>
        <CardDescription>Enter your email and we&apos;ll send you a reset link.</CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          {error && <p className="text-sm text-red-600">{error}</p>}
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" type="email" {...register('email')} />
            {errors.email && <p className="text-sm text-red-600">{errors.email.message}</p>}
          </div>
          <Button type="submit" className="w-full" disabled={isSubmitting}>
            {isSubmitting ? 'Sending…' : 'Send reset link'}
          </Button>
          <p className="text-center text-sm">
            <Link href="/login" className="text-slate-600 hover:text-slate-900">Back to sign in</Link>
          </p>
        </form>
      </CardContent>
    </Card>
  )
}

// pages/auth/reset-password.vue
<script setup lang="ts">
import { z } from 'zod'

definePageMeta({ layout: 'auth' })
useHead({ title: 'Reset Password – Muyenzi' })

const supabase = useSupabaseClient()
const state = reactive({ email: '' })
const sent = ref(false)
const loading = ref(false)
const error = ref<string | null>(null)

const schema = z.object({
  email: z.string().email('Please enter a valid email'),
})

async function onSubmit() {
  error.value = null
  loading.value = true
  const { error: resetError } = await supabase.auth.resetPasswordForEmail(state.email, {
    redirectTo: `${window.location.origin}/auth/update-password`,
  })
  loading.value = false
  if (resetError) {
    error.value = resetError.message
    return
  }
  sent.value = true
}
</script>

<template>
  <UCard>
    <template #header>
      <div>
        <h1 class="font-bold text-slate-900 text-xl">Reset your password</h1>
        <p class="text-sm text-slate-500 mt-0.5">Enter your email and we'll send a reset link</p>
      </div>
    </template>

    <div v-if="sent" class="text-center py-4">
      <UIcon name="i-lucide-mail-check" class="h-8 w-8 text-emerald-500 mx-auto mb-2" />
      <p class="text-sm text-slate-600">Check your inbox for a password reset link.</p>
    </div>

    <UForm v-else :schema="schema" :state="state" class="space-y-4" @submit="onSubmit">
      <UAlert v-if="error" color="red" variant="soft" :description="error" />
      <UFormGroup label="Email" name="email">
        <UInput v-model="state.email" type="email" placeholder="you@company.com" />
      </UFormGroup>
      <UButton type="submit" block :loading="loading">Send reset link</UButton>
    </UForm>

    <template #footer>
      <p class="text-center text-sm text-slate-500">
        <NuxtLink to="/login" class="font-medium text-slate-900 hover:underline">Back to sign in</NuxtLink>
      </p>
    </template>
  </UCard>
</template>
