// pages/dashboard/sites/new.vue
<script setup lang="ts">
import { z } from 'zod'

definePageMeta({ layout: 'dashboard' })
useHead({ title: 'New Site – Muyenzi' })

const supabase = useSupabaseClient()
const { user } = useUser()
const toast = useToast()

const state = reactive({ name: '', address: '' })
const loading = ref(false)

const schema = z.object({
  name: z.string().min(2, 'Site name is required'),
  address: z.string().optional(),
})

async function onSubmit() {
  if (!user.value) return
  loading.value = true
  const { error } = await supabase.from('sites').insert({
    company_id: user.value.company_id,
    name: state.name,
    address: state.address || null,
  })
  loading.value = false
  if (error) {
    toast.add({ title: 'Error', description: error.message, color: 'red' })
    return
  }
  toast.add({ title: 'Site created', color: 'green' })
  await navigateTo('/dashboard/sites')
}
</script>

<template>
  <div class="flex flex-col h-full">
    <LayoutTopbar title="New Site" />

    <div class="p-6 max-w-lg">
      <UButton variant="ghost" size="sm" to="/dashboard/sites" icon="i-lucide-arrow-left" class="mb-4 -ml-2">
        Back
      </UButton>
      <UCard>
        <template #header>
          <h2 class="font-bold text-gray-900">Add a new site</h2>
        </template>
        <UForm :schema="schema" :state="state" class="space-y-4" @submit="onSubmit">
          <UFormGroup label="Site name" name="name" required>
            <UInput v-model="state.name" placeholder="Head Office" />
          </UFormGroup>
          <UFormGroup label="Address" name="address">
            <UInput v-model="state.address" placeholder="123 Main Street, City" />
          </UFormGroup>
          <div class="flex gap-3 pt-2">
            <UButton variant="outline" @click="navigateTo('/dashboard/sites')">Cancel</UButton>
            <UButton type="submit" :loading="loading">Create Site</UButton>
          </div>
        </UForm>
      </UCard>
    </div>
  </div>
</template>

// src/app/(dashboard)/dashboard/sites/new/page.tsx
'use client'

import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import Topbar from '@/components/layout/Topbar'
import { useUser } from '@/context/UserContext'
import { toast } from 'sonner'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

const schema = z.object({
  name: z.string().min(2, 'Site name is required'),
  address: z.string().optional(),
})
type FormData = z.infer<typeof schema>

export default function NewSitePage() {
  const router = useRouter()
  const { user } = useUser()
  const supabase = createClient()

  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormData>({
    resolver: zodResolver(schema),
  })

  async function onSubmit(data: FormData) {
    if (!user) return
    const { error } = await supabase.from('sites').insert({
      company_id: user.company_id,
      name: data.name,
      address: data.address || null,
    })
    if (error) { toast.error(error.message); return }
    toast.success('Site created')
    router.push('/dashboard/sites')
    router.refresh()
  }

  return (
    <div className="flex flex-col">
      <Topbar title="New Site" />
      <div className="p-6 max-w-lg">
        <Button variant="ghost" size="sm" className="mb-4 -ml-2" asChild>
          <Link href="/dashboard/sites"><ArrowLeft className="h-4 w-4 mr-1" /> Back</Link>
        </Button>
        <Card>
          <CardHeader>
            <CardTitle>Add a new site</CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="name">Site name *</Label>
                <Input id="name" placeholder="Head Office" {...register('name')} />
                {errors.name && <p className="text-sm text-red-600">{errors.name.message}</p>}
              </div>
              <div className="space-y-2">
                <Label htmlFor="address">Address</Label>
                <Input id="address" placeholder="123 Main Street, City" {...register('address')} />
              </div>
              <div className="flex gap-3 pt-2">
                <Button type="button" variant="outline" onClick={() => router.back()}>Cancel</Button>
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting ? 'Creating…' : 'Create Site'}
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
