// src/components/invitations/InvitationForm.tsx
'use client'

import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Textarea } from '@/components/ui/textarea'
import { toast } from 'sonner'
import { generateAccessCode } from '@/lib/utils/access-code'
import QRCodeDisplay from '@/components/shared/QRCodeDisplay'
import { CheckCircle2, Copy } from 'lucide-react'

const schema = z.object({
  visitor_name: z.string().min(2, 'Visitor name is required'),
  visitor_company: z.string().optional(),
  visitor_email: z.string().email('Valid email required').optional().or(z.literal('')),
  visitor_phone: z.string().optional(),
  site_id: z.string().min(1, 'Please select a site'),
  host_id: z.string().min(1, 'Please select a host'),
  purpose: z.string().optional(),
  visit_date: z.string().min(1, 'Visit date is required'),
  visit_time: z.string().optional(),
  notes: z.string().optional(),
})
type FormData = z.infer<typeof schema>

interface Props {
  companyId: string
  hostId: string
  sites: { id: string; name: string }[]
  hosts: { id: string; full_name: string }[]
}

interface CreatedVisit {
  access_code: string
  qr_code_data: string
  visitor_name: string
}

export default function InvitationForm({ companyId, hostId, sites, hosts }: Props) {
  const router = useRouter()
  const supabase = createClient()
  const [created, setCreated] = useState<CreatedVisit | null>(null)

  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormData>({
    resolver: zodResolver(schema),
    defaultValues: {
      host_id: hostId,
      visit_date: new Date().toISOString().split('T')[0],
    },
  })

  async function onSubmit(data: FormData) {
    // 1. Upsert visitor
    const { data: visitor, error: visitorError } = await supabase
      .from('visitors')
      .upsert({
        company_id: companyId,
        full_name: data.visitor_name,
        email: data.visitor_email || null,
        phone: data.visitor_phone || null,
        company_name: data.visitor_company || null,
      }, { onConflict: 'company_id,email', ignoreDuplicates: false })
      .select()
      .single()

    if (visitorError || !visitor) {
      // If upsert fails (e.g. no email for dedup), just insert
      const { data: newVisitor, error } = await supabase
        .from('visitors')
        .insert({
          company_id: companyId,
          full_name: data.visitor_name,
          email: data.visitor_email || null,
          phone: data.visitor_phone || null,
          company_name: data.visitor_company || null,
        })
        .select()
        .single()
      if (error || !newVisitor) { toast.error('Failed to create visitor'); return }

      return finalizeVisit(data, newVisitor.id)
    }

    finalizeVisit(data, visitor.id)
  }

  async function finalizeVisit(data: FormData, visitorId: string) {
    const accessCode = generateAccessCode()
    const qrCodeData = JSON.stringify({ visitorId, siteId: data.site_id, accessCode, companyId })

    const { data: visit, error } = await supabase
      .from('visits')
      .insert({
        company_id: companyId,
        site_id: data.site_id,
        visitor_id: visitorId,
        host_id: data.host_id,
        purpose: data.purpose || null,
        visit_date: data.visit_date,
        visit_time: data.visit_time || null,
        notes: data.notes || null,
        access_code: accessCode,
        qr_code_data: qrCodeData,
        status: 'expected',
      })
      .select()
      .single()

    if (error || !visit) { toast.error(error?.message ?? 'Failed to create visit'); return }

    // Create invitation record
    await supabase.from('invitations').insert({ visit_id: visit.id })

    toast.success('Invitation created')
    setCreated({
      access_code: accessCode,
      qr_code_data: qrCodeData,
      visitor_name: data.visitor_name,
    })
  }

  if (created) {
    return (
      <div className="space-y-4">
        <Card className="border-emerald-200 bg-emerald-50">
          <CardContent className="pt-6 flex items-start gap-3">
            <CheckCircle2 className="h-5 w-5 text-emerald-600 mt-0.5 shrink-0" />
            <div>
              <p className="font-semibold text-emerald-900">Invitation created for {created.visitor_name}</p>
              <p className="text-sm text-emerald-700 mt-1">Share the QR code or access code with your visitor.</p>
            </div>
          </CardContent>
        </Card>

        <div className="grid md:grid-cols-2 gap-4">
          <Card>
            <CardHeader><CardTitle className="text-base">QR Code</CardTitle></CardHeader>
            <CardContent className="flex flex-col items-center gap-4">
              <QRCodeDisplay data={created.qr_code_data} size={200} />
              <p className="text-xs text-slate-500 text-center">Visitor scans this to check in</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader><CardTitle className="text-base">Access Code</CardTitle></CardHeader>
            <CardContent className="flex flex-col items-center justify-center gap-4 h-full">
              <div className="text-4xl font-mono font-bold tracking-wider text-slate-900 bg-slate-100 rounded-xl px-8 py-6">
                {created.access_code}
              </div>
              <button
                onClick={() => { navigator.clipboard.writeText(created.access_code); toast.success('Copied!') }}
                className="flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-900 transition-colors"
              >
                <Copy className="h-4 w-4" /> Copy code
              </button>
              <p className="text-xs text-slate-500 text-center">Visitor enters this code at reception</p>
            </CardContent>
          </Card>
        </div>

        <div className="flex gap-3">
          <Button variant="outline" onClick={() => router.push('/dashboard/invitations')}>View all invitations</Button>
          <Button onClick={() => { setCreated(null); router.refresh() }}>Create another</Button>
        </div>
      </div>
    )
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Pre-register a visitor</CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          {/* Visitor details */}
          <div>
            <h3 className="font-medium text-slate-900 mb-3">Visitor details</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Full name *</Label>
                <Input placeholder="Jane Smith" {...register('visitor_name')} />
                {errors.visitor_name && <p className="text-sm text-red-600">{errors.visitor_name.message}</p>}
              </div>
              <div className="space-y-2">
                <Label>Company</Label>
                <Input placeholder="Acme Corp" {...register('visitor_company')} />
              </div>
              <div className="space-y-2">
                <Label>Email</Label>
                <Input type="email" placeholder="jane@acme.com" {...register('visitor_email')} />
                {errors.visitor_email && <p className="text-sm text-red-600">{errors.visitor_email.message}</p>}
              </div>
              <div className="space-y-2">
                <Label>Phone</Label>
                <Input placeholder="+1 234 567 8900" {...register('visitor_phone')} />
              </div>
            </div>
          </div>

          {/* Visit details */}
          <div>
            <h3 className="font-medium text-slate-900 mb-3">Visit details</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Site *</Label>
                <select className="w-full text-sm border rounded-lg px-3 py-2 bg-white focus:outline-none focus:ring-2 focus:ring-slate-900" {...register('site_id')}>
                  <option value="">Select a site…</option>
                  {sites.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                </select>
                {errors.site_id && <p className="text-sm text-red-600">{errors.site_id.message}</p>}
              </div>
              <div className="space-y-2">
                <Label>Host *</Label>
                <select className="w-full text-sm border rounded-lg px-3 py-2 bg-white focus:outline-none focus:ring-2 focus:ring-slate-900" {...register('host_id')}>
                  <option value="">Select a host…</option>
                  {hosts.map(h => <option key={h.id} value={h.id}>{h.full_name}</option>)}
                </select>
                {errors.host_id && <p className="text-sm text-red-600">{errors.host_id.message}</p>}
              </div>
              <div className="space-y-2">
                <Label>Visit date *</Label>
                <Input type="date" {...register('visit_date')} />
                {errors.visit_date && <p className="text-sm text-red-600">{errors.visit_date.message}</p>}
              </div>
              <div className="space-y-2">
                <Label>Visit time</Label>
                <Input type="time" {...register('visit_time')} />
              </div>
              <div className="space-y-2 sm:col-span-2">
                <Label>Purpose of visit</Label>
                <Input placeholder="Business meeting, interview, delivery…" {...register('purpose')} />
              </div>
              <div className="space-y-2 sm:col-span-2">
                <Label>Notes</Label>
                <Textarea placeholder="Any additional notes…" rows={3} {...register('notes')} />
              </div>
            </div>
          </div>

          <div className="flex gap-3 pt-2">
            <Button type="button" variant="outline" onClick={() => router.back()}>Cancel</Button>
            <Button type="submit" disabled={isSubmitting}>
              {isSubmitting ? 'Creating invitation…' : 'Create Invitation'}
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  )
}

// components/invitations/InvitationForm.vue
<script setup lang="ts">
import { z } from 'zod'
import type { VisitorCustomField } from '~/types/database'

const props = defineProps<{
  companyId: string
  hostId: string
  sites: { id: string; name: string }[]
  hosts: { id: string; full_name: string }[]
}>()

const supabase = useSupabaseClient()
const toast = useToast()

interface CreatedVisit {
  access_code: string
  qr_code_data: string
  visitor_name: string
}

const created = ref<CreatedVisit | null>(null)
const loading = ref(false)

const customFields = ref<VisitorCustomField[]>([])
const customFieldValues = reactive<Record<string, string | number>>({})

watch(() => props.companyId, async (id) => {
  if (!id) return
  const data = await $fetch<VisitorCustomField[]>(`/api/visitor-fields?company_id=${id}`).catch(() => [])
  customFields.value = data
}, { immediate: true })

const state = reactive({
  visitor_name: '',
  visitor_company: '',
  visitor_email: '',
  visitor_phone: '',
  site_id: '',
  host_id: props.hostId,
  purpose: '',
  visit_date: new Date().toISOString().split('T')[0],
  visit_time: '',
  notes: '',
})

const schema = z.object({
  visitor_name: z.string().min(2, 'Visitor name is required'),
  visitor_company: z.string().optional(),
  visitor_email: z.string().email('Valid email required').optional().or(z.literal('')),
  visitor_phone: z.string().optional(),
  site_id: z.string().min(1, 'Please select a site'),
  host_id: z.string().min(1, 'Please select a host'),
  purpose: z.string().optional(),
  visit_date: z.string().min(1, 'Visit date is required'),
  visit_time: z.string().optional(),
  notes: z.string().optional(),
})

const siteOptions = computed(() => [
  { label: 'Select a site…', value: '' },
  ...props.sites.map(s => ({ label: s.name, value: s.id })),
])

const hostOptions = computed(() => [
  { label: 'Select a host…', value: '' },
  ...props.hosts.map(h => ({ label: h.full_name, value: h.id })),
])

async function onSubmit() {
  loading.value = true

  const { data: visitor, error: visitorError } = await supabase
    .from('visitors')
    .upsert({
      company_id: props.companyId,
      full_name: state.visitor_name,
      email: state.visitor_email || null,
      phone: state.visitor_phone || null,
      company_name: state.visitor_company || null,
    }, { onConflict: 'company_id,email', ignoreDuplicates: false })
    .select()
    .single()

  let visitorId = visitor?.id

  if (visitorError || !visitorId) {
    const { data: newVisitor, error } = await supabase
      .from('visitors')
      .insert({
        company_id: props.companyId,
        full_name: state.visitor_name,
        email: state.visitor_email || null,
        phone: state.visitor_phone || null,
        company_name: state.visitor_company || null,
      })
      .select()
      .single()

    if (error || !newVisitor) {
      toast.add({ title: 'Error', description: 'Failed to create visitor', color: 'red' })
      loading.value = false
      return
    }
    visitorId = newVisitor.id
  }

  const accessCode = generateAccessCode()
  const qrCodeData = JSON.stringify({ accessCode, siteId: state.site_id })

  const fieldValues = Object.keys(customFieldValues).length > 0 ? { ...customFieldValues } : null

  const { data: visit, error } = await supabase
    .from('visits')
    .insert({
      company_id: props.companyId,
      site_id: state.site_id,
      visitor_id: visitorId,
      host_id: state.host_id,
      purpose: state.purpose || null,
      visit_date: state.visit_date,
      visit_time: state.visit_time || null,
      notes: state.notes || null,
      access_code: accessCode,
      qr_code_data: qrCodeData,
      status: 'expected',
      custom_field_values: fieldValues,
    })
    .select()
    .single()

  if (error || !visit) {
    toast.add({ title: 'Error', description: error?.message ?? 'Failed to create visit', color: 'red' })
    loading.value = false
    return
  }

  await supabase.from('invitations').insert({ visit_id: visit.id })

  toast.add({ title: 'Invitation created', color: 'green' })
  created.value = { access_code: accessCode, qr_code_data: qrCodeData, visitor_name: state.visitor_name }
  loading.value = false
}

function copyCode() {
  if (!created.value) return
  navigator.clipboard.writeText(created.value.access_code)
  toast.add({ title: 'Copied!', timeout: 1500 })
}

function createAnother() {
  created.value = null
  Object.assign(state, {
    visitor_name: '', visitor_company: '', visitor_email: '', visitor_phone: '',
    site_id: '', host_id: props.hostId, purpose: '',
    visit_date: new Date().toISOString().split('T')[0], visit_time: '', notes: '',
  })
  Object.keys(customFieldValues).forEach(k => delete customFieldValues[k])
}
</script>

<template>
  <!-- Success state -->
  <div v-if="created" class="space-y-4 max-w-2xl">
    <UAlert
      icon="i-lucide-check-circle-2"
      color="green"
      variant="soft"
      :title="`Invitation created for ${created.visitor_name}`"
      description="Share the QR code or access code with your visitor."
    />

    <div class="grid md:grid-cols-2 gap-4">
      <UCard>
        <template #header><h3 class="font-semibold text-gray-900">QR Code</h3></template>
        <div class="flex flex-col items-center gap-4">
          <SharedQRCodeDisplay :data="created.qr_code_data" :size="200" />
          <p class="text-xs text-gray-400 text-center">Visitor scans this to check in</p>
        </div>
      </UCard>
      <UCard>
        <template #header><h3 class="font-semibold text-gray-900">Access Code</h3></template>
        <div class="flex flex-col items-center justify-center gap-4 h-full py-4">
          <div class="text-4xl font-mono font-bold tracking-wider text-gray-900 bg-gray-100 rounded-xl px-8 py-5">
            {{ created.access_code }}
          </div>
          <button class="flex items-center gap-1.5 text-sm text-gray-400 hover:text-gray-900 transition-colors" @click="copyCode">
            <UIcon name="i-lucide-copy" class="h-4 w-4" />
            Copy code
          </button>
          <p class="text-xs text-gray-400 text-center">Visitor enters this code at reception</p>
        </div>
      </UCard>
    </div>

    <div class="flex gap-3">
      <UButton variant="outline" to="/dashboard/invitations">View all invitations</UButton>
      <UButton @click="createAnother">Create another</UButton>
    </div>
  </div>

  <!-- Form -->
  <UCard v-else class="max-w-2xl">
    <template #header>
      <h2 class="font-bold text-gray-900">Pre-register a visitor</h2>
    </template>

    <UForm :schema="schema" :state="state" class="space-y-6" @submit="onSubmit">
      <!-- Visitor details -->
      <div>
        <h3 class="font-medium text-gray-700 mb-3 text-sm">Visitor details</h3>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <UFormGroup label="Full name" name="visitor_name" required>
            <UInput v-model="state.visitor_name" placeholder="Jane Smith" />
          </UFormGroup>
          <UFormGroup label="Company" name="visitor_company">
            <UInput v-model="state.visitor_company" placeholder="Acme Corp" />
          </UFormGroup>
          <UFormGroup label="Email" name="visitor_email">
            <UInput v-model="state.visitor_email" type="email" placeholder="jane@acme.com" />
          </UFormGroup>
          <UFormGroup label="Phone" name="visitor_phone">
            <UInput v-model="state.visitor_phone" placeholder="+1 234 567 8900" />
          </UFormGroup>
        </div>
      </div>

      <!-- Visit details -->
      <div>
        <h3 class="font-medium text-gray-700 mb-3 text-sm">Visit details</h3>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <UFormGroup label="Site" name="site_id" required>
            <USelect v-model="state.site_id" :options="siteOptions" />
          </UFormGroup>
          <UFormGroup label="Host" name="host_id" required>
            <USelect v-model="state.host_id" :options="hostOptions" />
          </UFormGroup>
          <UFormGroup label="Visit date" name="visit_date" required>
            <UInput v-model="state.visit_date" type="date" />
          </UFormGroup>
          <UFormGroup label="Visit time" name="visit_time">
            <UInput v-model="state.visit_time" type="time" />
          </UFormGroup>
          <UFormGroup label="Purpose of visit" name="purpose" class="sm:col-span-2">
            <UInput v-model="state.purpose" placeholder="Business meeting, interview, delivery…" />
          </UFormGroup>
          <UFormGroup label="Notes" name="notes" class="sm:col-span-2">
            <UTextarea v-model="state.notes" placeholder="Any additional notes…" :rows="3" />
          </UFormGroup>
        </div>
      </div>

      <!-- Custom fields -->
      <div v-if="customFields.length > 0">
        <h3 class="font-medium text-gray-700 mb-3 text-sm">Additional information</h3>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <UFormGroup
            v-for="field in customFields"
            :key="field.id"
            :label="field.label"
            :required="field.required"
            :class="field.field_type === 'textarea' ? 'sm:col-span-2' : ''"
          >
            <USelect
              v-if="field.field_type === 'select'"
              v-model="customFieldValues[field.field_key]"
              :options="[{ label: 'Select…', value: '' }, ...(field.options ?? []).map(o => ({ label: o, value: o }))]"
            />
            <UTextarea
              v-else-if="field.field_type === 'textarea'"
              v-model="customFieldValues[field.field_key]"
              :rows="3"
            />
            <UInput
              v-else
              v-model="customFieldValues[field.field_key]"
              :type="field.field_type === 'number' ? 'number' : 'text'"
            />
          </UFormGroup>
        </div>
      </div>

      <div class="flex gap-3 pt-2">
        <UButton variant="outline" @click="navigateTo('/dashboard/invitations')">Cancel</UButton>
        <UButton type="submit" :loading="loading">Create Invitation</UButton>
      </div>
    </UForm>
  </UCard>
</template>
