// components/dashboard/RecentVisitsTable.vue
<script setup lang="ts">
import type { VisitWithRelations } from '~/types/database'

defineProps<{
  visits: VisitWithRelations[]
  loading?: boolean
}>()

const STATUS_COLORS: Record<string, string> = {
  expected: 'blue',
  checked_in: 'green',
  checked_out: 'gray',
  cancelled: 'red',
  no_show: 'yellow',
}

const STATUS_LABELS: Record<string, string> = {
  expected: 'Expected',
  checked_in: 'Checked In',
  checked_out: 'Checked Out',
  cancelled: 'Cancelled',
  no_show: 'No Show',
}
</script>

<template>
  <div v-if="loading" class="py-8 text-center text-gray-400 text-sm animate-pulse">Loading…</div>

  <div v-else-if="visits.length === 0" class="py-12 text-center">
    <p class="text-sm text-gray-400">No visits yet</p>
  </div>

  <div v-else class="overflow-x-auto">
    <table class="w-full text-sm">
      <thead>
        <tr class="border-b border-gray-100">
          <th v-for="col in ['Visitor', 'Site', 'Check In', 'Status']" :key="col"
            class="text-left px-4 py-3 text-[11px] font-bold uppercase tracking-widest text-gray-400"
          >
            {{ col }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="(visit, i) in visits"
          :key="visit.id"
          class="hover:bg-gray-50 transition-colors"
          :class="{ 'border-b border-gray-100': i < visits.length - 1 }"
        >
          <td class="px-4 py-3">
            <p class="font-semibold text-gray-900">{{ visit.visitor.full_name }}</p>
            <p v-if="visit.visitor.company_name" class="text-xs text-gray-400">{{ visit.visitor.company_name }}</p>
          </td>
          <td class="px-4 py-3 text-gray-500 text-xs">{{ visit.site.name }}</td>
          <td class="px-4 py-3 text-gray-400 text-xs whitespace-nowrap">
            {{ visit.check_in_at ? formatDateTime(visit.check_in_at) : '—' }}
          </td>
          <td class="px-4 py-3">
            <UBadge :color="STATUS_COLORS[visit.status]" variant="soft" size="sm">
              {{ STATUS_LABELS[visit.status] }}
            </UBadge>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// src/components/dashboard/RecentVisitsTable.tsx
import Link from 'next/link'
import { Chip } from '@heroui/react'
import { formatDateTime } from '@/lib/utils/format'
import type { VisitWithRelations } from '@/types/database'
import { Users } from 'lucide-react'

type StatusKey = 'expected' | 'checked_in' | 'checked_out' | 'cancelled' | 'no_show'

const STATUS_CONFIG: Record<StatusKey, { label: string; color: 'primary' | 'success' | 'default' | 'danger' | 'warning' }> = {
  expected:    { label: 'Expected',    color: 'primary' },
  checked_in:  { label: 'Checked In',  color: 'success' },
  checked_out: { label: 'Checked Out', color: 'default' },
  cancelled:   { label: 'Cancelled',   color: 'danger' },
  no_show:     { label: 'No Show',     color: 'warning' },
}

export default function RecentVisitsTable({ visits }: { visits: VisitWithRelations[] }) {
  if (visits.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <div className="h-14 w-14 rounded-full bg-default-100 flex items-center justify-center mb-3">
          <Users className="h-7 w-7 text-default-300" />
        </div>
        <p className="text-sm font-semibold text-foreground mb-1">No visits yet today</p>
        <p className="text-xs text-default-400">Visits will appear here as they come in</p>
      </div>
    )
  }

  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm">
        <thead>
          <tr style={{ borderBottom: '1px solid var(--border)' }}>
            {['Visitor', 'Host', 'Site', 'Time', 'Status'].map(col => (
              <th key={col} className="pb-3 text-left text-[11px] font-bold uppercase tracking-widest text-default-400 pr-4">
                {col}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {visits.map((visit, i) => {
            const cfg = STATUS_CONFIG[visit.status as StatusKey] ?? STATUS_CONFIG.expected
            return (
              <tr
                key={visit.id}
                className="group transition-colors"
                style={{
                  borderBottom: i < visits.length - 1 ? '1px solid var(--border)' : 'none',
                }}
              >
                <td className="py-3.5 pr-4">
                  <Link
                    href={`/dashboard/visitors/${visit.visitor_id}`}
                    className="font-semibold text-foreground hover:text-primary transition-colors"
                  >
                    {visit.visitor.full_name}
                  </Link>
                  {visit.visitor.company_name && (
                    <p className="text-xs text-default-400 mt-0.5">{visit.visitor.company_name}</p>
                  )}
                </td>
                <td className="py-3.5 pr-4 text-default-500 text-sm">
                  {visit.host?.full_name ?? '—'}
                </td>
                <td className="py-3.5 pr-4 text-default-500 text-sm">
                  {visit.site.name}
                </td>
                <td className="py-3.5 pr-4 text-default-400 text-xs whitespace-nowrap">
                  {visit.check_in_at ? formatDateTime(visit.check_in_at) : formatDateTime(visit.created_at)}
                </td>
                <td className="py-3.5">
                  <Chip
                    color={cfg.color}
                    variant="flat"
                    size="sm"
                    radius="full"
                    classNames={{ content: 'text-xs font-semibold' }}
                  >
                    {cfg.label}
                  </Chip>
                </td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}
