// src/app/(dashboard)/dashboard/users/page.tsx
import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import Topbar from '@/components/layout/Topbar'
import { Card, CardContent } from '@/components/ui/card'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { ROLE_LABELS } from '@/lib/constants/roles'
import type { UserRole } from '@/types/database'
import ChangeRoleButton from './ChangeRoleButton'

export const metadata = { title: 'Team – Muyenzi' }

export default async function UsersPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: profile } = await supabase.from('users').select('company_id, role').eq('id', user.id).single()
  if (!profile) redirect('/login')
  if (profile.role !== 'admin') redirect('/dashboard')

  const { data: users } = await supabase
    .from('users')
    .select('*')
    .eq('company_id', profile.company_id)
    .order('created_at', { ascending: true })

  const ROLE_COLORS: Record<UserRole, string> = {
    admin: 'bg-purple-50 text-purple-700 border-purple-200',
    site_manager: 'bg-blue-50 text-blue-700 border-blue-200',
    receptionist: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    host: 'bg-slate-50 text-slate-700 border-slate-200',
  }

  return (
    <div className="flex flex-col">
      <Topbar title="Team" />
      <div className="p-6 space-y-4">
        <p className="text-sm text-slate-500">{users?.length ?? 0} team member{users?.length !== 1 ? 's' : ''}</p>
        <Card>
          <CardContent className="p-0">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b bg-slate-50">
                  <th className="text-left px-4 py-3 font-medium text-slate-600">Member</th>
                  <th className="text-left px-4 py-3 font-medium text-slate-600">Email</th>
                  <th className="text-left px-4 py-3 font-medium text-slate-600">Role</th>
                  <th className="text-left px-4 py-3 font-medium text-slate-600">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {(users ?? []).map(u => {
                  const initials = u.full_name?.split(' ').map((n: string) => n[0]).join('').toUpperCase().slice(0, 2) ?? '?'
                  return (
                    <tr key={u.id} className="hover:bg-slate-50">
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-3">
                          <Avatar className="h-8 w-8">
                            <AvatarFallback className="text-xs bg-slate-200">{initials}</AvatarFallback>
                          </Avatar>
                          <span className="font-medium text-slate-900">{u.full_name}</span>
                          {u.id === user.id && <span className="text-xs text-slate-400">(you)</span>}
                        </div>
                      </td>
                      <td className="px-4 py-3 text-slate-600">{u.email}</td>
                      <td className="px-4 py-3">
                        <span className={`inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium ${ROLE_COLORS[u.role as UserRole]}`}>
                          {ROLE_LABELS[u.role as UserRole]}
                        </span>
                      </td>
                      <td className="px-4 py-3">
                        {u.id !== user.id && (
                          <ChangeRoleButton userId={u.id} currentRole={u.role as UserRole} />
                        )}
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

// pages/dashboard/users.vue
<script setup lang="ts">
import { ROLE_LABELS } from '~/constants/roles'
import type { User, UserRole } from '~/types/database'

definePageMeta({ layout: 'dashboard' })
useHead({ title: 'Team – Muyenzi' })

const supabase = useSupabaseClient()
const { user } = useUser()
const toast = useToast()

const users = ref<User[]>([])
const loading = ref(true)

const ROLE_COLORS: Record<UserRole, string> = {
  admin: 'purple',
  site_manager: 'blue',
  receptionist: 'green',
  host: 'gray',
}

const roleOptions: { label: string; value: UserRole }[] = [
  { label: 'Admin', value: 'admin' },
  { label: 'Site Manager', value: 'site_manager' },
  { label: 'Receptionist', value: 'receptionist' },
  { label: 'Host', value: 'host' },
]

onMounted(async () => {
  if (!user.value) return
  if (user.value.role !== 'admin') {
    await navigateTo('/dashboard')
    return
  }
  const { data } = await supabase
    .from('users')
    .select('*')
    .eq('company_id', user.value.company_id)
    .order('created_at', { ascending: true })
  users.value = (data ?? []) as User[]
  loading.value = false
})

async function changeRole(userId: string, role: UserRole) {
  const { error } = await supabase.from('users').update({ role }).eq('id', userId)
  if (error) {
    toast.add({ title: 'Error', description: error.message, color: 'red' })
    return
  }
  users.value = users.value.map(u => u.id === userId ? { ...u, role } : u)
  toast.add({ title: 'Role updated', color: 'green' })
}

function initials(name: string) {
  return name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2)
}
</script>

<template>
  <div class="flex flex-col h-full">
    <LayoutTopbar title="Team" description="Manage your team members and their roles" />

    <div class="flex-1 overflow-y-auto p-6 space-y-4">
      <p class="text-sm text-gray-400">{{ users.length }} team member{{ users.length !== 1 ? 's' : '' }}</p>

      <UCard :ui="{ body: { padding: '' } }">
        <div class="overflow-x-auto">
          <table class="w-full text-sm">
            <thead>
              <tr class="border-b border-gray-100 bg-gray-50">
                <th v-for="col in ['Member', 'Email', 'Role', 'Actions']" :key="col"
                  class="text-left px-4 py-3 text-xs font-bold uppercase tracking-widest text-gray-400"
                >
                  {{ col }}
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-100">
              <tr v-for="u in users" :key="u.id" class="hover:bg-gray-50">
                <td class="px-4 py-3">
                  <div class="flex items-center gap-3">
                    <UAvatar :alt="initials(u.full_name)" size="sm" />
                    <span class="font-medium text-gray-900">{{ u.full_name }}</span>
                    <UBadge v-if="u.id === user?.id" color="gray" variant="soft" size="xs">you</UBadge>
                  </div>
                </td>
                <td class="px-4 py-3 text-gray-500">{{ u.email }}</td>
                <td class="px-4 py-3">
                  <UBadge :color="ROLE_COLORS[u.role as UserRole]" variant="soft" size="sm">
                    {{ ROLE_LABELS[u.role as UserRole] }}
                  </UBadge>
                </td>
                <td class="px-4 py-3">
                  <USelect
                    v-if="u.id !== user?.id"
                    :model-value="u.role"
                    :options="roleOptions"
                    size="sm"
                    class="w-36"
                    @update:model-value="(role: UserRole) => changeRole(u.id, role)"
                  />
                </td>
              </tr>
            </tbody>
          </table>
          <div v-if="loading" class="p-8 text-center text-gray-400 text-sm">Loading…</div>
        </div>
      </UCard>
    </div>
  </div>
</template>
