// pages/dashboard/analytics.vue
<script setup lang="ts">
definePageMeta({ layout: 'dashboard' })
useHead({ title: 'Analytics – Muyenzi' })

const supabase = useSupabaseClient()
const { user } = useUser()

const trends = ref<{ visit_date: string; visit_count: number }[]>([])
const hourly = ref<{ hour: number; visit_count: number }[]>([])
const siteData = ref<{ name: string; count: number }[]>([])
const currentlyInside = ref(0)
const loading = ref(true)

onMounted(async () => {
  if (!user.value) return
  const companyId = user.value.company_id

  const [{ data: t }, { data: h }, { data: s }] = await Promise.all([
    supabase.rpc('get_visit_trends', { p_company_id: companyId, p_days: 30 }),
    supabase.rpc('get_hourly_distribution', { p_company_id: companyId, p_days: 30 }),
    supabase.from('visits').select('site_id, site:sites(name), status').eq('company_id', companyId).neq('status', 'cancelled'),
  ])

  trends.value = (t ?? []) as typeof trends.value
  hourly.value = (h ?? []) as typeof hourly.value

  const siteMap = new Map<string, { name: string; count: number }>()
  for (const v of s ?? []) {
    const siteName = (v.site as unknown as { name: string })?.name ?? 'Unknown'
    const existing = siteMap.get(v.site_id) ?? { name: siteName, count: 0 }
    siteMap.set(v.site_id, { ...existing, count: existing.count + 1 })
  }
  siteData.value = Array.from(siteMap.values()).sort((a, b) => b.count - a.count)
  currentlyInside.value = (s ?? []).filter(v => v.status === 'checked_in').length
  loading.value = false
})
</script>

<template>
  <div class="flex flex-col h-full">
    <LayoutTopbar title="Analytics" description="Last 30 days of visitor activity" />

    <div class="flex-1 overflow-y-auto p-6 space-y-6">
      <div class="flex items-center justify-between">
        <p class="text-sm text-gray-400 font-medium">30-day overview</p>
        <SharedExportMenu :company-id="user?.company_id ?? ''" />
      </div>

      <!-- Active visitors alert -->
      <UAlert
        v-if="currentlyInside > 0"
        color="yellow"
        variant="soft"
        icon="i-lucide-activity"
        :description="`${currentlyInside} visitor${currentlyInside !== 1 ? 's' : ''} currently inside the building`"
      />

      <div class="grid grid-cols-1 xl:grid-cols-2 gap-6">
        <UCard>
          <template #header>
            <h3 class="font-bold text-gray-900">Visitor Trends (30 days)</h3>
          </template>
          <AnalyticsVisitTrendsChart :data="trends" />
        </UCard>

        <UCard>
          <template #header>
            <h3 class="font-bold text-gray-900">Peak Hours</h3>
          </template>
          <AnalyticsHourlyChart :data="hourly" />
        </UCard>
      </div>

      <UCard>
        <template #header>
          <h3 class="font-bold text-gray-900">Visits by Site</h3>
        </template>
        <AnalyticsSiteBreakdown :data="siteData" />
      </UCard>
    </div>
  </div>
</template>

// src/app/(dashboard)/dashboard/analytics/page.tsx
import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { Card, CardBody, CardHeader } from '@heroui/react'
import Topbar from '@/components/layout/Topbar'
import VisitTrendsChart from '@/components/analytics/VisitTrendsChart'
import HourlyChart from '@/components/analytics/HourlyChart'
import SiteBreakdown from '@/components/analytics/SiteBreakdown'
import ExportMenu from '@/components/shared/ExportMenu'

export const metadata = { title: 'Analytics – Muyenzi' }

export default async function AnalyticsPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: profile } = await supabase.from('users').select('company_id').eq('id', user.id).single()
  if (!profile) redirect('/login')

  const companyId = profile.company_id

  const [{ data: trends }, { data: hourly }, { data: sites }] = await Promise.all([
    supabase.rpc('get_visit_trends', { p_company_id: companyId, p_days: 30 }),
    supabase.rpc('get_hourly_distribution', { p_company_id: companyId, p_days: 30 }),
    supabase
      .from('visits')
      .select('site_id, site:sites(name), status')
      .eq('company_id', companyId)
      .neq('status', 'cancelled'),
  ])

  const siteMap = new Map<string, { name: string; count: number }>()
  for (const v of sites ?? []) {
    const siteName = (v.site as unknown as { name: string })?.name ?? 'Unknown'
    const existing = siteMap.get(v.site_id) ?? { name: siteName, count: 0 }
    siteMap.set(v.site_id, { ...existing, count: existing.count + 1 })
  }
  const siteData = Array.from(siteMap.values()).sort((a, b) => b.count - a.count)
  const currentlyInside = (sites ?? []).filter(v => v.status === 'checked_in').length

  return (
    <div className="flex flex-col h-full">
      <Topbar title="Analytics" description="Last 30 days of visitor activity" />

      <div className="flex-1 overflow-y-auto p-6 space-y-6">
        <div className="flex items-center justify-between">
          <p className="text-sm text-default-400 font-medium">30-day overview</p>
          <ExportMenu companyId={companyId} />
        </div>

        {/* Active visitors alert */}
        {currentlyInside > 0 && (
          <Card
            shadow="none"
            radius="lg"
            className="border border-warning/30"
            style={{ background: 'rgba(245,158,11,0.06)' }}
          >
            <CardBody className="py-3.5 px-5 flex flex-row items-center gap-3">
              <span className="h-2.5 w-2.5 rounded-full bg-warning animate-pulse shrink-0" />
              <p className="text-sm font-semibold text-warning">
                {currentlyInside} visitor{currentlyInside !== 1 ? 's' : ''} currently inside the building
              </p>
            </CardBody>
          </Card>
        )}

        <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
          <Card shadow="md" radius="lg" className="bg-content1">
            <CardHeader className="px-6 py-4" style={{ borderBottom: '1px solid var(--border)' }}>
              <h3 className="font-bold text-foreground text-base">Visitor Trends (30 days)</h3>
            </CardHeader>
            <CardBody className="px-6 py-4">
              <VisitTrendsChart data={(trends ?? []) as { visit_date: string; visit_count: number }[]} />
            </CardBody>
          </Card>

          <Card shadow="md" radius="lg" className="bg-content1">
            <CardHeader className="px-6 py-4" style={{ borderBottom: '1px solid var(--border)' }}>
              <h3 className="font-bold text-foreground text-base">Peak Hours</h3>
            </CardHeader>
            <CardBody className="px-6 py-4">
              <HourlyChart data={(hourly ?? []) as { hour: number; visit_count: number }[]} />
            </CardBody>
          </Card>
        </div>

        <Card shadow="md" radius="lg" className="bg-content1">
          <CardHeader className="px-6 py-4" style={{ borderBottom: '1px solid var(--border)' }}>
            <h3 className="font-bold text-foreground text-base">Visits by Site</h3>
          </CardHeader>
          <CardBody className="px-6 py-4">
            <SiteBreakdown data={siteData} />
          </CardBody>
        </Card>
      </div>
    </div>
  )
}
